### PR TITLE
SlowPlace, fixes #105

### LINKED ISSUE #105: SlowPlace (hack suggestion)
When you have timer set to 3x speed, placing blocks can be very very fast. Sometimes when I'm trying to make a wall or a ceiling, especially out of blocks like obsidian, I make so many mistakes and I spend so much time fixing them with a diamond pickaxe I just wish there was a hack that did the opposite of FastPlace: Make it so the cooldown is always set, so blocks only get placed on right-click.

### PR DESCRIPTION
**Pull request by LoganDark**
SlowPlace.
- Timer sync - the most important feature. Prevents timer from speeding up your block placement.
- Factor - control the speed of block placement. This is a multiplier. 2 makes you place blocks 2x slower, 0.5x makes you place it 2x faster, and 0 is the same as FastPlace.
- Single - what was outlined in my issue #105. Only allows placing one block per click, no matter how much your hold it down.

### CODE REVIEW

**Comment by VADemon** [comment]
https://github.com/fr1kin/ForgeHax/blob/master/src/main/java/com/matt/forgehax/mods/FastPlaceMod.java ?

**Comment by LoganDark** [comment]
Yes, that is what inspired the name. FastPlace makes you place blocks very fast, SlowPlace is meant to slow things down when you're using Timer if you don't need to spam blocks.

**Comment by VADemon** [comment]
Yes this is great, but there will be a conflict when both mods are enabled. 
Maybe: Temp. disable FastPlace when this is enabled and auto-disable itself when its detected FastPlace was turned on? ↖ fr1kin?

**Comment by LoganDark** [comment]
> Yes this is great, but there will be a conflict when both mods are enabled.

I could just remove FastPlace, rename this to Place, and then you could set the factor to 0 for the exact same FastPlace behavior.

**Comment by fr1kin** [comment]
Just edit FastPlace instead.

**Comment by LoganDark** [comment]
@fr1kin FastPlace wouldn't be a good name for it anymore though. I thought Place would serve both purposes, if you REALLY want me to combine the two.

**Comment by fr1kin** [comment]
I thought the point of 'slowing down' fast place was to allow it to place at a normal speed when using the timer mod?

**Comment by LoganDark** [comment]
@fr1kin Yes, the purpose of this mod is to keep block placement at a sane speed even with Timer on. FastPlace's purpose is to place blocks as fast as possible no matter what.

This mod allows me to use levers with timer on. :>

**Comment by fr1kin** [comment]
I think it should remain named FastPlace so that it remains grouped with FastBreak. I know it wont make sense, but the slowness features main use is to sync with the timer.

**Comment by LoganDark** [comment]
Mkay, well I'll set up the defaults to be identical to the old FastPlace, then move all the settings into FastPlace

**Comment by fr1kin** [comment]
Confirmed everything working?

**Comment by LoganDark** [comment]
@fr1kin yep

**Comment by fr1kin** [comment]
Just an update. I am putting PRs on hold until I get my cleanup branch merged with master. I am debating whether I should re-add spotless or not and I'll probably decide what I'll do this weekend.

**Comment by LoganDark** [comment]
Okay then, have fun

**Pull request closed without merging**
