### PR TITLE
Add continuous integration using the nhack industries Jenkins server

### PR DESCRIPTION
**Pull request by starcraft66**
Further configuration on the main repo will need to be done for the github webhooks and having jenkins test build pull requests and merges etc.

### CODE REVIEW

**Comment by DaMatrix** [comment]
y tho

**Comment by starcraft66** [comment]
Hello, I am aware that this project had a link to your jenkins server building the project for quite some time. We have determined that using our own continuous integration server would be better suited for this project's needs (building all branches concurrently, building open pull requests and making sure they work, updating the build status on the github web interface and more).

**Comment by DaMatrix** [comment]
okey dokey! just wanted to know is all

**Comment by swall-bit** [comment]
Release nhack???

**Pull request merged**
