### PR TITLE
Feature/gui lines

### PR DESCRIPTION
**Pull request by IronException**
The GeometryMask Lines has previously drawn the 2 complete sides around the line. That is probably unintended. This should fix that problem.

https://cdn.discordapp.com/attachments/686121398778986527/733653737146679326/unknown.png
https://cdn.discordapp.com/attachments/686121398778986527/733653930449305651/unknown.png

### CODE REVIEW

**Comment by fr1kin** [comment]
I am sort of confused as to why the Lunatrius developer does it this way. Seems really strange...

0x11 = 10001
0x12 = 10010
0x21 = 100001

smh

**Comment by VADemon** [comment]
Are you sure there's no mistake? Why do you pass `LINES` to the cuboid draw function? Drawing "cuboid" with SOUTH_EAST makes sense to draw lines around two sides of a single block

+ the constant for LINES seem to be the same as for QUADS bitwise-OR'ed: https://github.com/fr1kin/ForgeHax/blob/master/src/main/java/com/matt/forgehax/util/tesselation/GeometryMasks.java so WHYEVER he decided to hardcode them again instead of OR-ing in these lines

PS: Note1: Sigh at smoothie-dev screenshot of code
Note2: The tessellator could do with a face lift to allow using ints for positions instead forcing to use blockpos

**Comment by fr1kin** [comment]
I don't think its a mistake, I just don't get why he did it like this. SOUTH_EAST would imply it would draw the south and east sides, which from the screenshot appears to be what it is doing? 

>The tessellator could do with a face lift to allow using ints for positions instead forcing to use blockpos
In ForgeHax 3.0 I just god rid of this mess entirely. I am thinking of eventually backporting to to 1.12

**Comment by IronException** [comment]
> 
> 
> Are you sure there's no mistake? Why do you pass `LINES` to the cuboid draw function? Drawing "cuboid" with SOUTH_EAST makes sense to draw lines around two sides of a single block
> 
> + the constant for LINES seem to be the same as for QUADS bitwise-OR'ed: https://github.com/fr1kin/ForgeHax/blob/master/src/main/java/com/matt/forgehax/util/tesselation/GeometryMasks.java so WHYEVER he decided to hardcode them again instead of OR-ing in these lines
> 
> PS: Note1: Sigh at smoothie-dev screenshot of code
> Note2: The tessellator could do with a face lift to allow using ints for positions instead forcing to use blockpos

Looking it in that way it makes sense actually. However I think there should be another mask to only draw one line then because currently there is no way to do that.

**Comment by IronException** [comment]
I added the changes that @VADemon suggested and changed the mod that could be improved (I thought there where more that that tbh)

**Comment by IronException** [comment]
What is the plan about line rendering?

**Comment by fr1kin** [comment]
I'm like 90% sure it was done in this way to minimize the number of vertexes drawn. I think your changes would break that

**Pull request merged**
