### PR TITLE
Fixes #111 and #109

### LINKED ISSUE #111: Step off of chests
This issue is related to #109.

You can't step up from chests, you have to jump.

This could be solved by making the step height slightly higher, like 1.1.

### PR DESCRIPTION
**Pull request by LoganDark**

### CODE REVIEW

**Comment by LoganDark** [comment]
I made this edit from GitHub's UI since I don't know how to build and test this myself, so please do test before merging.

**Comment by bowwychan** [comment]
why 1.1? chests are shorter so it should be 0.9 but that would fuck up everything else

**Comment by LoganDark** [comment]
@bowwychan chests are shorter so you need to step higher to get off of them. 🤦‍♂

**Comment by bowwychan** [comment]
🤡

**Comment by LoganDark** [comment]
With this fix you should be able to step up from village paths as well, since I've confirmed you can't do that either. There's a reason vanilla uses 0.6 instead of 0.5, and this is it.

**Comment by fr1kin** [comment]
Probably should just allow a custom step height to be specified, and default it to 1.1f.

**Comment by LoganDark** [comment]
Yes please. I could probably write out some code based on the other mods but I won't be able to test it.

**Comment by LoganDark** [comment]
Here we go, some untested code fresh out of the GitHub web interface, should work fine

**Comment by LoganDark** [comment]
Ooh, Jenkins auto-generates artifacts. Let's see if I can shove this into my own client and test it out myself...

**Comment by LoganDark** [comment]
@bowwychan theoretically it'll update the next time you jump or go into the air at any time. I will perform tests, and if it doesn't perform to my liking, I will research how to retrieve the local player and update it immediately.

**Comment by LoganDark** [comment]
It updates basically every tick so that's not necessary. 1.1 is not high enough though.

**Comment by LoganDark** [comment]
@fr1kin This PR is ready for merge, I have tested it and it works to my liking. 1.2 is sufficient for stepping up from chests. 2 step works on vanilla servers. I haven't tested higher numbers yet but this seems to work perfectly. I may have to make one more commit though as the `.2f` looks kind of annoying.

**Comment by fr1kin** [comment]
👍

**Pull request merged**
