### PR TITLE
New waifu esp

### PR DESCRIPTION
**Pull request by allbombson**
https://github.com/forgehax/assets/pull/1 for the PR to add new picture. https://github.com/fr1kin/ForgeHax/pull/141 for old pr.

### CODE REVIEW

**Comment by VADemon** [comment]
Pls decline i dont wanna get hard every time i play minceraft

**Comment by babbaj** [comment]
this is an improvement

**Comment by 0-x-2-2** [comment]
cringe

**Comment by allbombson** [comment]
BRUH. man of no culture.

**Comment by cookiedragon234** [comment]
wtf not ok

**Pull request closed without merging**
